#!/usr/bin/env python3
"""Embed compiled .hsaco code objects into a generated catalog .cpp.

Each argument is a `<name>=<path.hsaco>` pair. `name` is both the catalog lookup
key and the kernel's extern "C" entry-point symbol. The generated file defines a
byte array per kernel plus a linear-scan lookup implementing catalog.h.

    embed_catalog.py --output catalog_generated.cpp add=add.hsaco mul=mul.hsaco
"""

from __future__ import annotations

import argparse
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Embed .hsaco files into a catalog .cpp.")
    parser.add_argument("-o", "--output", type=Path, required=True, help="generated .cpp path")
    parser.add_argument("kernels", nargs="+", help="<name>=<path.hsaco> pairs")
    return parser.parse_args()


def emit_array(name: str, data: bytes) -> str:
    lines = [f"alignas(16) static const unsigned char k_{name}[] = {{"]
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};\n")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()

    kernels = [pair.split("=", 1) for pair in args.kernels]

    out = ['// Generated by embed_catalog.py. Do not edit.',
           '#include "catalog.h"',
           "#include <cstring>",
           ""]

    for name, path in kernels:
        out.append(emit_array(name, Path(path).read_bytes()))

    out.append("static const hsaco_entry k_catalog[] = {")
    for name, _ in kernels:
        out.append(f'    {{ "{name}", k_{name}, sizeof(k_{name}) }},')
    out.append("};\n")

    out.append("const hsaco_entry * hsaco_catalog_find(const char * name) {")
    out.append("    for (const auto & e : k_catalog) {")
    out.append("        if (std::strcmp(e.name, name) == 0) return &e;")
    out.append("    }")
    out.append("    return nullptr;")
    out.append("}")

    args.output.write_text("\n".join(out) + "\n")
    print(f"== wrote {args.output} ({len(kernels)} kernel(s))", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
